# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker image build -t toonhudsha/app:$TAG .
          docker image push to toonhudsha/app:$TAG